In [2]:
import pandas as pd
import sys
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [8]:
temp = "drop_as"
temp = list(temp.split('_'))
temp[1]


'as'

In [11]:
df = pd.read_csv("insurance.csv")
df

color      director_name  num_critic_for_reviews  duration  \
0     Color      James Cameron                   723.0     178.0   
1     Color     Gore Verbinski                   302.0     169.0   
2     Color         Sam Mendes                   602.0     148.0   
3     Color  Christopher Nolan                   813.0     164.0   
4       NaN        Doug Walker                     NaN       NaN   
...     ...                ...                     ...       ...   
5038  Color        Scott Smith                     1.0      87.0   
5039  Color                NaN                    43.0      43.0   
5040  Color   Benjamin Roberds                    13.0      76.0   
5041  Color        Daniel Hsia                    14.0     100.0   
5042  Color           Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore   
1                       563.0                  1000.0     Orlando Bloom   
2                         0.0                   161.0      Rory Kinnear   
3                     22000.0                 23000.0    Christian Bale   
4                       131.0                     NaN        Rob Walker   
...                       ...                     ...               ...   
5038                      2.0                   318.0     Daphne Zuniga   
5039                      NaN                   319.0     Valorie Curry   
5040                      0.0                     0.0     Maxwell Moody   
5041                      0.0                   489.0     Daniel Henney   
5042                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes        gross                           genres  \
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                    40000.0  309404152.0         Action|Adventure|Fantasy   
2                    11000.0  200074175.0        Action|Adventure|Thriller   
3                    27000.0  448130642.0                  Action|Thriller   
4                      131.0          NaN                      Documentary   
...                      ...          ...                              ...   
5038                   637.0          NaN                     Comedy|Drama   
5039                   841.0          NaN     Crime|Drama|Mystery|Thriller   
5040                     0.0          NaN            Drama|Horror|Thriller   
5041                   946.0      10443.0             Comedy|Drama|Romance   
5042                    86.0      85222.0                      Documentary   

      ... num_user_for_reviews language  country  content_rating       budget  \
0     ...               3054.0  English      USA           PG-13  237000000.0   
1     ...               1238.0  English      USA           PG-13  300000000.0   
2     ...                994.0  English       UK           PG-13  245000000.0   
3     ...               2701.0  English      USA           PG-13  250000000.0   
4     ...                  NaN      NaN      NaN             NaN          NaN   
...   ...                  ...      ...      ...             ...          ...   
5038  ...                  6.0  English   Canada             NaN          NaN   
5039  ...                359.0  English      USA           TV-14          NaN   
5040  ...                  3.0  English      USA             NaN       1400.0   
5041  ...                  9.0  English      USA           PG-13          NaN   
5042  ...                 84.0  English      USA              PG       1100.0   

      title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0         2009.0                  936.0        7.9          1.78   
1         2007.0                 5000.0        7.1          2.35   
2         2015.0                  393.0        6.8          2.35   
3         2012.0                23000.0        8.5          2.35   
4            NaN                   12.

In [10]:
df.drop("sex",axis=1)

KeyError: "['sex'] not found in axis"

In [4]:
drop(df,"Gender")
pd.read_csv("temp_data.csv")

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")
df

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [8]:
dff = pd.read_csv("insurance.csv")
dff

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
df = OHot(df)
df

NameError: name 'OHot' is not defined

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.2,random_state=0)
int(len(X_train)**(1/2))

17

In [21]:
dff = pd.read_csv("movie_metadata.csv")

In [ ]:
dff = 

In [27]:
dff

color      director_name  num_critic_for_reviews  duration  \
0     Color      James Cameron                   723.0     178.0   
1     Color     Gore Verbinski                   302.0     169.0   
2     Color         Sam Mendes                   602.0     148.0   
3     Color  Christopher Nolan                   813.0     164.0   
4       NaN        Doug Walker                     NaN       NaN   
...     ...                ...                     ...       ...   
5038  Color        Scott Smith                     1.0      87.0   
5039  Color                NaN                    43.0      43.0   
5040  Color   Benjamin Roberds                    13.0      76.0   
5041  Color        Daniel Hsia                    14.0     100.0   
5042  Color           Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore   
1                       563.0                  1000.0     Orlando Bloom   
2                         0.0                   161.0      Rory Kinnear   
3                     22000.0                 23000.0    Christian Bale   
4                       131.0                     NaN        Rob Walker   
...                       ...                     ...               ...   
5038                      2.0                   318.0     Daphne Zuniga   
5039                      NaN                   319.0     Valorie Curry   
5040                      0.0                     0.0     Maxwell Moody   
5041                      0.0                   489.0     Daniel Henney   
5042                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes        gross                           genres  \
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                    40000.0  309404152.0         Action|Adventure|Fantasy   
2                    11000.0  200074175.0        Action|Adventure|Thriller   
3                    27000.0  448130642.0                  Action|Thriller   
4                      131.0          NaN                      Documentary   
...                      ...          ...                              ...   
5038                   637.0          NaN                     Comedy|Drama   
5039                   841.0          NaN     Crime|Drama|Mystery|Thriller   
5040                     0.0          NaN            Drama|Horror|Thriller   
5041                   946.0      10443.0             Comedy|Drama|Romance   
5042                    86.0      85222.0                      Documentary   

      ... num_user_for_reviews language  country  content_rating       budget  \
0     ...               3054.0  English      USA           PG-13  237000000.0   
1     ...               1238.0  English      USA           PG-13  300000000.0   
2     ...                994.0  English       UK           PG-13  245000000.0   
3     ...               2701.0  English      USA           PG-13  250000000.0   
4     ...                  NaN      NaN      NaN             NaN          NaN   
...   ...                  ...      ...      ...             ...          ...   
5038  ...                  6.0  English   Canada             NaN          NaN   
5039  ...                359.0  English      USA           TV-14          NaN   
5040  ...                  3.0  English      USA             NaN       1400.0   
5041  ...                  9.0  English      USA           PG-13          NaN   
5042  ...                 84.0  English      USA              PG       1100.0   

      title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0         2009.0                  936.0        7.9          1.78   
1         2007.0                 5000.0        7.1          2.35   
2         2015.0                  393.0        6.8          2.35   
3         2012.0                23000.0        8.5          2.35   
4            NaN                   12.

In [15]:
def OHot(df):
    ctg = df.select_dtypes(include=['object']).columns.tolist()
    oneh = OneHotEncoder(sparse=False)
    temp = pd.DataFrame(oneh.fit_transform(df[ctg]),columns = oneh.get_feature_names_out(ctg))
    df = pd.concat([temp,df.drop(ctg,axis=1)],axis=1)
    return df

In [16]:
dff = OHot(dff)

In [19]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Columns: 26715 entries, color_ Black and White to movie_facebook_likes
dtypes: float64(26712), int64(3)
memory usage: 1.0 GB


In [18]:
import numpy as np
from numpy.linalg import svd

A = np.array([[1, 2, np.nan],
              [4, np.nan, 6],
              [7, 8, 9]])


matrix = np.array(A)
missing_mask = np.isnan(matrix)
print(missing_mask)


[[False False  True]
 [False  True False]
 [False False False]]


In [19]:
# Initialize missing values to column means
col_mean = np.nanmean(matrix, axis=0)
inds = np.where(np.isnan(matrix))
matrix[inds] = np.take(col_mean, inds[1])
col_mean

array([4. , 5. , 7.5])

In [25]:

for _ in range(100):
    U, s, Vt = svd(matrix, full_matrices=False)
    print(U,s,Vt)
    S = np.diag(s)
    matrix_hat = np.dot(U, np.dot(S, Vt))
    print(matrix_hat)
    matrix[missing_mask] = matrix_hat[missing_mask]
    print(matrix[missing_mask])
    if np.linalg.norm(matrix[missing_mask] - matrix_hat[missing_mask]) < 1e-5:
        break

[[-0.38972454  0.91609284  0.09427983]
 [-0.4924086  -0.12077354 -0.86194404]
 [-0.77823426 -0.38234494  0.4981604 ]] [17.79081606  3.9623464   0.19150736] [[-0.43882184 -0.53214906 -0.72405301]
 [-0.56618369 -0.46195899  0.68266385]
 [ 0.69776172 -0.70951481  0.09857642]]
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]
[7.5 5. ]


In [4]:
# dff = pd.read_csv("movie_metadata.csv")
# for cols in dff.items():
#     print(cols[0]," ",dff[cols[0]].nunique())

for cols in dff.items():
    if(dff[cols[0]].nunique()>20 and dff[cols[0]].dtype=='object'):
        dff.drop(cols[0],axis=1,inplace=True)
dff

color  num_critic_for_reviews  duration  director_facebook_likes  \
0     Color                   723.0     178.0                      0.0   
1     Color                   302.0     169.0                    563.0   
2     Color                   602.0     148.0                      0.0   
3     Color                   813.0     164.0                  22000.0   
4       NaN                     NaN       NaN                    131.0   
...     ...                     ...       ...                      ...   
5038  Color                     1.0      87.0                      2.0   
5039  Color                    43.0      43.0                      NaN   
5040  Color                    13.0      76.0                      0.0   
5041  Color                    14.0     100.0                      0.0   
5042  Color                    43.0      90.0                     16.0   

      actor_3_facebook_likes  actor_1_facebook_likes        gross  \
0                      855.0                  1000.0  760505847.0   
1                     1000.0                 40000.0  309404152.0   
2                      161.0                 11000.0  200074175.0   
3                    23000.0                 27000.0  448130642.0   
4                        NaN                   131.0          NaN   
...                      ...                     ...          ...   
5038                   318.0                   637.0          NaN   
5039                   319.0                   841.0          NaN   
5040                     0.0                     0.0          NaN   
5041                   489.0                   946.0      10443.0   
5042                    16.0                    86.0      85222.0   

      num_voted_users  cast_total_facebook_likes  facenumber_in_poster  \
0              886204                       4834                   0.0   
1              471220                      48350                   0.0   
2              275868                      11700                   1.0   
3             1144337                     106759                   0.0   
4                   8                        143                   0.0   
...               ...                        ...                   ...   
5038              629                       2283                   2.0   
5039            73839                       1753                   1.0   
5040               38                          0                   0.0   
5041             1255                       2386                   5.0   
5042             4285                        163                   0.0   

      num_user_for_reviews content_rating       budget  title_year  \
0                   3054.0          PG-13  237000000.0      2009.0   
1                   1238.0          PG-13  300000000.0      2007.0   
2                    994.0          PG-13  245000000.0      2015.0   
3                   2701.0          PG-13  250000000.0      2012.0   
4                      NaN            NaN          NaN         NaN   
...                    ...            ...          ...         ...   
5038                   6.0            NaN          NaN      2013.0   
5039                 359.0          TV-14          NaN         NaN   
5040                   3.0            NaN       1400.0      2013.0   
5041                   9.0          PG-13          NaN      2012.0   
5042                  84.0             PG       1100.0      2004.0   

      actor_2_facebook_likes  imdb_score  aspect_ratio  movie_facebook_likes  
0                      936.0         7.9          1.78                 33000  
1                     5000.0         7.1          2.35                     0  
2                      393.0         6.8          2.35                 85000  
3                    23000.0         8.5          2.35                164000  
4                       12.0         7.1           NaN                     0  
...                      ...         ...           ...                   ...  
5038 

In [9]:
dff

color  num_critic_for_reviews  duration  director_facebook_likes  \
0     Color                   723.0     178.0                      0.0   
1     Color                   302.0     169.0                    563.0   
2     Color                   602.0     148.0                      0.0   
3     Color                   813.0     164.0                  22000.0   
4       NaN                     NaN       NaN                    131.0   
...     ...                     ...       ...                      ...   
5038  Color                     1.0      87.0                      2.0   
5039  Color                    43.0      43.0                      NaN   
5040  Color                    13.0      76.0                      0.0   
5041  Color                    14.0     100.0                      0.0   
5042  Color                    43.0      90.0                     16.0   

      actor_3_facebook_likes  actor_1_facebook_likes        gross  \
0                      855.0                  1000.0  760505847.0   
1                     1000.0                 40000.0  309404152.0   
2                      161.0                 11000.0  200074175.0   
3                    23000.0                 27000.0  448130642.0   
4                        NaN                   131.0          NaN   
...                      ...                     ...          ...   
5038                   318.0                   637.0          NaN   
5039                   319.0                   841.0          NaN   
5040                     0.0                     0.0          NaN   
5041                   489.0                   946.0      10443.0   
5042                    16.0                    86.0      85222.0   

      num_voted_users  cast_total_facebook_likes  facenumber_in_poster  \
0              886204                       4834                   0.0   
1              471220                      48350                   0.0   
2              275868                      11700                   1.0   
3             1144337                     106759                   0.0   
4                   8                        143                   0.0   
...               ...                        ...                   ...   
5038              629                       2283                   2.0   
5039            73839                       1753                   1.0   
5040               38                          0                   0.0   
5041             1255                       2386                   5.0   
5042             4285                        163                   0.0   

      num_user_for_reviews content_rating       budget  title_year  \
0                   3054.0          PG-13  237000000.0      2009.0   
1                   1238.0          PG-13  300000000.0      2007.0   
2                    994.0          PG-13  245000000.0      2015.0   
3                   2701.0          PG-13  250000000.0      2012.0   
4                      NaN            NaN          NaN         NaN   
...                    ...            ...          ...         ...   
5038                   6.0            NaN          NaN      2013.0   
5039                 359.0          TV-14          NaN         NaN   
5040                   3.0            NaN       1400.0      2013.0   
5041                   9.0          PG-13          NaN      2012.0   
5042                  84.0             PG       1100.0      2004.0   

      actor_2_facebook_likes  imdb_score  aspect_ratio  movie_facebook_likes  
0                      936.0         7.9          1.78                 33000  
1                     5000.0         7.1          2.35                     0  
2                      393.0         6.8          2.35                 85000  
3                    23000.0         8.5          2.35                164000  
4                       12.0         7.1           NaN                     0  
...                      ...         ...           ...                   ...  
5038 

In [22]:
import pandas as pd
import sys
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier



def OHot(df):
    ctg = df.select_dtypes(include=['object']).columns.tolist()
    oneh = OneHotEncoder(sparse=False)
    temp = pd.DataFrame(oneh.fit_transform(df[ctg]),columns = oneh.get_feature_names_out(ctg))
    df = pd.concat([temp,df.drop(ctg,axis=1)],axis=1)
    return df






In [31]:
X_train, X_test, Y_train, Y_test = train_test_split(dff.iloc[:,:-1],dff.iloc[:,-1],test_size=0.2,random_state=0)
lr = LogisticRegression()
model_lr = lr.fit(X_train,Y_train)
print("lr")
print(model_lr.score(X_test,Y_test))

lr
0.4400396432111001


c:\Users\Er-Pr\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [6]:
def svd_impute(matrix, max_iter=100, tol=1e-5):
    matrix = np.array(matrix)
    missing_mask = np.isnan(matrix)
    
    col_mean = np.nanmean(matrix, axis=0)
    inds = np.where(np.isnan(matrix))
    matrix[inds] = np.take(col_mean, inds[1])

    for _ in range(max_iter):
        U, s, Vt = np.linalg.svd(matrix, full_matrices=False)
        S = np.diag(s)
        matrix_hat = np.dot(U, np.dot(S, Vt))
        
        matrix[missing_mask] = matrix_hat[missing_mask]
        if np.linalg.norm(matrix[missing_mask] - matrix_hat[missing_mask]) < tol:
            break

    return matrix

In [7]:
dff = svd_impute(dff)
dff = pd.DataFrame(dff)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [30]:
dff

0    1    2    3    4    5    6    7    8    9   ...         28  \
0     0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   886204.0   
1     0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   471220.0   
2     0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   275868.0   
3     0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1144337.0   
4     0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...        8.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...        ...   
5038  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...      629.0   
5039  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    73839.0   
5040  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...       38.0   
5041  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...     1255.0   
5042  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...     4285.0   

            29   30           31            32           33       34   35  \
0       4834.0  0.0  3054.000000  2.370000e+08  2009.000000    936.0  7.9   
1      48350.0  0.0  1238.000000  3.000000e+08  2007.000000   5000.0  7.1   
2      11700.0  1.0   994.000000  2.450000e+08  2015.000000    393.0  6.8   
3     106759.0  0.0  2701.000000  2.500000e+08  2012.000000  23000.0  8.5   
4        143.0  0.0   272.770808  3.975262e+07  2002.470517     12.0  7.1   
...        ...  ...          ...           ...          ...      ...  ...   
5038    2283.0  2.0     6.000000  3.975262e+07  2013.000000    470.0  7.7   
5039    1753.0  1.0   359.000000  3.975262e+07  2002.470517    593.0  7.5   
5040       0.0  0.0     3.000000  1.400000e+03  2013.000000      0.0  6.3   
5041    2386.0  5.0     9.000000  3.975262e+07  2012.000000    719.0  6.3   
5042     163.0  0.0    84.000000  1.100000e+03  2004.000000     23.0  6.6   

             36        37  
0      1.780000   33000.0  
1      2.350000       0.0  
2      2.350000   85000.0  
3      2.350000  164000.0  
4      2.220403       0.0  
...         ...       ...  
5038   2.220403      84.0  
5039  16.000000   32000.0  
5040   2.220403      16.0  
5041   2.350000     660.0  
5042   1.850000     456.0  

[5043 rows x 38 columns]

In [32]:
dff.to_csv("tess.csv")